// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating personalized feedback on quiz answers.
 *
 * - `generateFeedback`: A function that takes a question, the user's answer, and the correct answer,
 *   and returns personalized feedback explaining why the user's answer was correct or incorrect.
 * - `GenerateFeedbackInput`: The input type for the `generateFeedback` function.
 * - `GenerateFeedbackOutput`: The output type for the `generateFeedback` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateFeedbackInputSchema = z.object({
  question: z.string().describe('The quiz question.'),
  userAnswer: z.string().describe('The user selected answer.'),
  correctAnswer: z.string().describe('The correct answer to the question.'),
});

export type GenerateFeedbackInput = z.infer<typeof GenerateFeedbackInputSchema>;

const GenerateFeedbackOutputSchema = z.object({
  feedback: z.string().describe('Personalized feedback explaining why the user answer was correct or incorrect.'),
});

export type GenerateFeedbackOutput = z.infer<typeof GenerateFeedbackOutputSchema>;

export async function generateFeedback(input: GenerateFeedbackInput): Promise<GenerateFeedbackOutput> {
  return generateFeedbackFlow(input);
}

const generateFeedbackPrompt = ai.definePrompt({
  name: 'generateFeedbackPrompt',
  input: {schema: GenerateFeedbackInputSchema},
  output: {schema: GenerateFeedbackOutputSchema},
  prompt: `You are an expert quiz feedback generator. Given a quiz question, the user's answer, and the correct answer, your job is to provide personalized feedback to the user.

  If the user's answer is correct, explain why it is correct and provide additional insights about the topic.
  If the user's answer is incorrect, explain why it is incorrect and guide the user towards the correct answer.

  Question: {{{question}}}
  User's Answer: {{{userAnswer}}}
  Correct Answer: {{{correctAnswer}}} `,
});

const generateFeedbackFlow = ai.defineFlow(
  {
    name: 'generateFeedbackFlow',
    inputSchema: GenerateFeedbackInputSchema,
    outputSchema: GenerateFeedbackOutputSchema,
  },
  async input => {
    const {output} = await generateFeedbackPrompt(input);
    return output!;
  }
);
